name: heatsink
path: datasets/heatsink  # if data is not available at the given path, it will be downloaded
normalization: zscore
difficulty: medium
out_deformation: False
space: 3
n_subsampled_nodes: 16000
